In [1]:
import numpy as np

In [10]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array(range(n**2), dtype = dtype).reshape(n,n)

In [11]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type == 0:
        return np.zeros(shape=shape, dtype=dtype)
    if type == 1:
        return np.ones(shape=shape, dtype=dtype)
    if type == 99:
        return np.empty(shape=shape, dtype=dtype)

In [13]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row == 1 else X.reshape(n_row, -1)

X = zero_or_one_or_empty_ndarray((32,32),1)
change_shape_of_ndarray(X,1)

array([1, 1, 1, ..., 1, 1, 1])

In [5]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1,-1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1,-1)
        return np.concatenate((X_1,X_2), axis=axis)
    except ValueError as e:
        return False

In [14]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column = X.shape
    if axis == 99:
        x_mean = np.mean(X)
        x_std = np.std(X)
        Z = (X - x_mean) / x_std
    if axis == 0:
        x_mean = np.mean(X,0).reshape(1,-1)
        x_std = np.std(X,0).reshape(1,-1)
        Z = (X - x_mean) / x_std
    if axis == 1:
        x_mean = np.mean(X,1).reshape(n_row, -1)
        x_std = np.std(X, 1).reshape(n_row, -1)
        Z = (X - x_mean) / x_std
    return Z

X = np.arange(12, dtype = np.float32).reshape(4,3)
normalize_ndarray(X)

array([[-1.593255  , -1.3035723 , -1.0138896 ],
       [-0.7242068 , -0.4345241 , -0.14484136],
       [ 0.14484136,  0.4345241 ,  0.7242068 ],
       [ 1.0138896 ,  1.3035723 ,  1.593255  ]], dtype=float32)

In [7]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename, "wb")
    np.save(X, file_test)

In [17]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

X = np.arange(32, dtype=np.float32)
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [18]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

X = np.random.uniform(0,1,5)
target_value = 0.3
np.abs(X-target_value)

array([0.46899997, 0.48260222, 0.49234617, 0.40928834, 0.34367875])

In [19]:
find_nearest_value(X,target_value)

0.6436787531343203

In [20]:
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

X = np.random.uniform(0,1,5)
get_n_largest_values(X, 3)

array([0.29705905, 0.29297722, 0.92512253])